FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

COPY server.py /app/server.py

COPY proxies.txt /app/proxies.txt

COPY settings.yaml /app/settings.yaml

EXPOSE 8002

CMD ["python", "/app/server.py"]
