client:
  token: ""
  server_id: 782869253258739742
  excluded_channels:
    - 0
  regex_filter: ""

server:
  token: ""
  server_id: 782869253258739742 
  interval: 60
  webhook_name: "Test"
  websocket:
    port: 5000
    host: "0.0.0.0"